import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
export const accounts = sqliteTable("accounts", {
  id: text().primaryKey(),
  platform: text().notNull(),
  label: text().notNull(),
  profileId: text().notNull(),
  workspaceId: text().notNull(),
  identity: text().notNull(),
  notes: text().notNull().default(""),
  version: integer().notNull(),
  status: text().notNull(),
  reason: text().notNull().default(""),
  updatedAt: integer().notNull(),
  validatedAt: integer(),
  nextAllowedAt: integer().notNull().default(0),
  secret: text().notNull(),
  lease: text(),
  leaseUntil: integer(),
});
export const tasks = sqliteTable("tasks", {
  id: text().primaryKey(),
  requestId: text().notNull().unique(),
  accountId: text().notNull(),
  status: text().notNull(),
  input: text().notNull(),
  result: text(),
  error: text(),
  createdAt: integer().notNull(),
  updatedAt: integer().notNull(),
  deadline: integer().notNull(),
  pages: integer().notNull().default(0),
  cancelled: integer().notNull().default(0),
  lease: text(),
});
